name: Test Deploy

on:
  workflow_dispatch:  # 手动触发

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    # 简单的连接测试
    - name: Test SSH Connection and Environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        debug: true
        script: |
          echo "========== 基本信息 =========="
          echo "连接时间: $(date)"
          echo "主机名: $(hostname)"
          echo "当前用户: $(whoami)"
          echo "当前目录: $(pwd)"
          echo "系统信息: $(uname -a)"
          echo "Shell: $SHELL"
          
          echo "========== 路径检查 =========="
          echo "环境变量 PATH: $PATH"
          echo "Home 目录: $HOME"
          
          echo "检查可能的项目路径:"
          echo "1. /c/wwwroot/"
          ls -la /c/wwwroot/ 2>/dev/null || echo "  - 不存在"
          
          echo "2. C:/wwwroot/"
          ls -la "C:/wwwroot/" 2>/dev/null || echo "  - 不存在"
          
          echo "3. /mnt/c/wwwroot/"
          ls -la /mnt/c/wwwroot/ 2>/dev/null || echo "  - 不存在"
          
          echo "4. /cygdrive/c/wwwroot/"
          ls -la /cygdrive/c/wwwroot/ 2>/dev/null || echo "  - 不存在"
          
          echo "5. ~/wwwroot/"
          ls -la ~/wwwroot/ 2>/dev/null || echo "  - 不存在"
          
          echo "搜索 game_box 目录:"
          find / -name "game_box" -type d 2>/dev/null | head -10 || echo "搜索失败"
          
          echo "========== Git 检查 =========="
          which git || echo "Git 不在 PATH 中"
          git --version 2>/dev/null || echo "Git 命令失败"
          
          echo "========== Node.js 检查 =========="
          which node || echo "Node 不在 PATH 中"
          node --version 2>/dev/null || echo "Node 命令失败"
          
          which npm || echo "NPM 不在 PATH 中"
          npm --version 2>/dev/null || echo "NPM 命令失败"
          
          echo "检查 NVM:"
          if [ -f ~/.nvm/nvm.sh ]; then
            echo "找到 NVM，加载中..."
            source ~/.nvm/nvm.sh
            nvm --version 2>/dev/null || echo "NVM 加载失败"
            nvm list 2>/dev/null || echo "NVM list 失败"
          else
            echo "未找到 NVM"
          fi
          
          echo "========== PM2 检查 =========="
          which pm2 || echo "PM2 不在 PATH 中"
          pm2 --version 2>/dev/null || echo "PM2 命令失败"
          
          echo "========== 磁盘空间 =========="
          df -h 2>/dev/null || echo "磁盘检查失败"
          
          echo "========== 进程信息 =========="
          ps aux | grep -E "(node|npm|pm2)" | head -5 || echo "进程检查失败"
          
          echo "========== 测试完成 ==========" 